// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from '@prismicio/client';

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };

type PickContentRelationshipFieldData<
  TRelationship extends
    | prismic.CustomTypeModelFetchCustomTypeLevel1
    | prismic.CustomTypeModelFetchCustomTypeLevel2
    | prismic.CustomTypeModelFetchGroupLevel1
    | prismic.CustomTypeModelFetchGroupLevel2,
  TData extends Record<
    string,
    | prismic.AnyRegularField
    | prismic.GroupField
    | prismic.NestedGroupField
    | prismic.SliceZone
  >,
  TLang extends string,
> =
  // Content relationship fields
  {
    [TSubRelationship in Extract<
      TRelationship['fields'][number],
      prismic.CustomTypeModelFetchContentRelationshipLevel1
    > as TSubRelationship['id']]: ContentRelationshipFieldWithData<
      TSubRelationship['customtypes'],
      TLang
    >;
  } & // Group
  {
    [TGroup in Extract<
      TRelationship['fields'][number],
      | prismic.CustomTypeModelFetchGroupLevel1
      | prismic.CustomTypeModelFetchGroupLevel2
    > as TGroup['id']]: TData[TGroup['id']] extends prismic.GroupField<
      infer TGroupData
    >
      ? prismic.GroupField<
          PickContentRelationshipFieldData<TGroup, TGroupData, TLang>
        >
      : never;
  } & // Other fields
  {
    [TFieldKey in Extract<
      TRelationship['fields'][number],
      string
    >]: TFieldKey extends keyof TData ? TData[TFieldKey] : never;
  };

type ContentRelationshipFieldWithData<
  TCustomType extends
    | readonly (prismic.CustomTypeModelFetchCustomTypeLevel1 | string)[]
    | readonly (prismic.CustomTypeModelFetchCustomTypeLevel2 | string)[],
  TLang extends string = string,
> = {
  [ID in Exclude<
    TCustomType[number],
    string
  >['id']]: prismic.ContentRelationshipField<
    ID,
    TLang,
    PickContentRelationshipFieldData<
      Extract<TCustomType[number], { id: ID }>,
      Extract<prismic.Content.AllDocumentTypes, { type: ID }>['data'],
      TLang
    >
  >;
}[Exclude<TCustomType[number], string>['id']];

type AboutUsDocumentDataSlicesSlice =
  | AboutJohnSlice
  | WhatWeDoSlice
  | TimelineSectionSlice
  | CallToActionSlice
  | OurMissionSlice
  | SubpageHeroSectionSlice;

/**
 * Content for About Us documents
 */
interface AboutUsDocumentData {
  /**
   * Slice Zone field in *About Us*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: about_us.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/slices
   */
  slices: prismic.SliceZone<AboutUsDocumentDataSlicesSlice>; /**
   * Meta Title field in *About Us*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: about_us.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *About Us*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: about_us.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *About Us*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: about_us.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * About Us document from Prismic
 *
 * - **API ID**: `about_us`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type AboutUsDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<AboutUsDocumentData>,
    'about_us',
    Lang
  >;

type ContractorModuleDocumentDataSlicesSlice =
  | SubpageHeroSectionSlice
  | ComplianceAuditSlice
  | BulletListSlice
  | FaqSlice;

/**
 * Content for Contractor Module documents
 */
interface ContractorModuleDocumentData {
  /**
   * Slice Zone field in *Contractor Module*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: contractor_module.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/slices
   */
  slices: prismic.SliceZone<ContractorModuleDocumentDataSlicesSlice>; /**
   * Meta Title field in *Contractor Module*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: contractor_module.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Contractor Module*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: contractor_module.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Contractor Module*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: contractor_module.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * Contractor Module document from Prismic
 *
 * - **API ID**: `contractor_module`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type ContractorModuleDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<ContractorModuleDocumentData>,
    'contractor_module',
    Lang
  >;

type FormsModuleDocumentDataSlicesSlice =
  | ComplianceAuditSlice
  | BulletListSlice
  | SubpageHeroSectionSlice
  | FaqSlice;

/**
 * Content for Forms Module documents
 */
interface FormsModuleDocumentData {
  /**
   * Slice Zone field in *Forms Module*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: forms_module.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/slices
   */
  slices: prismic.SliceZone<FormsModuleDocumentDataSlicesSlice>; /**
   * Meta Title field in *Forms Module*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: forms_module.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Forms Module*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: forms_module.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Forms Module*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: forms_module.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * Forms Module document from Prismic
 *
 * - **API ID**: `forms_module`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type FormsModuleDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<FormsModuleDocumentData>,
    'forms_module',
    Lang
  >;

type HazardModuleDocumentDataSlicesSlice =
  | SubpageHeroSectionSlice
  | ComplianceAuditSlice
  | BulletListSlice
  | FaqSlice;

/**
 * Content for Hazard Module documents
 */
interface HazardModuleDocumentData {
  /**
   * Slice Zone field in *Hazard Module*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: hazard_module.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/slices
   */
  slices: prismic.SliceZone<HazardModuleDocumentDataSlicesSlice>; /**
   * Meta Title field in *Hazard Module*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: hazard_module.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Hazard Module*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: hazard_module.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Hazard Module*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: hazard_module.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * Hazard Module document from Prismic
 *
 * - **API ID**: `hazard_module`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type HazardModuleDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<HazardModuleDocumentData>,
    'hazard_module',
    Lang
  >;

type HomeDocumentDataSlicesSlice =
  | FaqSlice
  | ContactUsSlice
  | CallToActionSlice
  | HowWeCanWelpSlice
  | WhyChooseUsSlice
  | FinancialReliefSlice
  | LegislativeSlice
  | PlatformAppsSlice
  | CompaniesSlice
  | HeroSectionSlice
  | TestimonialSlice;

/**
 * Content for Home documents
 */
interface HomeDocumentData {
  /**
   * Slice Zone field in *Home*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: home.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/slices
   */
  slices: prismic.SliceZone<HomeDocumentDataSlicesSlice>; /**
   * Meta Title field in *Home*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: home.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Home*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: home.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Home*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: home.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * Home document from Prismic
 *
 * - **API ID**: `home`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type HomeDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<Simplify<HomeDocumentData>, 'home', Lang>;

type InspectionModuleDocumentDataSlicesSlice =
  | SubpageHeroSectionSlice
  | CallToActionSlice
  | BulletListSlice
  | ComplianceAuditSlice
  | FaqSlice;

/**
 * Content for Inspection Module documents
 */
interface InspectionModuleDocumentData {
  /**
   * Slice Zone field in *Inspection Module*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: inspection_module.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/slices
   */
  slices: prismic.SliceZone<InspectionModuleDocumentDataSlicesSlice>; /**
   * Meta Title field in *Inspection Module*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: inspection_module.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Inspection Module*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: inspection_module.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Inspection Module*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: inspection_module.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * Inspection Module document from Prismic
 *
 * - **API ID**: `inspection_module`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type InspectionModuleDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<InspectionModuleDocumentData>,
    'inspection_module',
    Lang
  >;

type PageDocumentDataSlicesSlice =
  | CallToActionSlice
  | CompaniesSlice
  | ComplianceAuditSlice
  | ContactUsSlice
  | FaqSlice
  | FinancialReliefSlice
  | HeroSectionSlice
  | HowWeCanWelpSlice
  | LegislativeSlice
  | PlatformAppsSlice
  | TestimonialSlice
  | WhyChooseUsSlice;

/**
 * Content for Page documents
 */
interface PageDocumentData {
  /**
   * Slice Zone field in *Page*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: page.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/slices
   */
  slices: prismic.SliceZone<PageDocumentDataSlicesSlice>; /**
   * Meta Title field in *Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: page.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: page.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Page*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: page.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * Page document from Prismic
 *
 * - **API ID**: `page`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type PageDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<Simplify<PageDocumentData>, 'page', Lang>;

type PoliciesModuleDocumentDataSlicesSlice =
  | SubpageHeroSectionSlice
  | ComplianceAuditSlice
  | BulletListSlice
  | FaqSlice;

/**
 * Content for Policies Module documents
 */
interface PoliciesModuleDocumentData {
  /**
   * Slice Zone field in *Policies Module*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: policies_module.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/slices
   */
  slices: prismic.SliceZone<PoliciesModuleDocumentDataSlicesSlice>; /**
   * Meta Title field in *Policies Module*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: policies_module.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Policies Module*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: policies_module.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Policies Module*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: policies_module.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * Policies Module document from Prismic
 *
 * - **API ID**: `policies_module`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type PoliciesModuleDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<PoliciesModuleDocumentData>,
    'policies_module',
    Lang
  >;

type TrainingModuleDocumentDataSlicesSlice =
  | SubpageHeroSectionSlice
  | BulletListSlice
  | ComplianceAuditSlice
  | FaqSlice;

/**
 * Content for Training Module documents
 */
interface TrainingModuleDocumentData {
  /**
   * Slice Zone field in *Training Module*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: training_module.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/slices
   */
  slices: prismic.SliceZone<TrainingModuleDocumentDataSlicesSlice>; /**
   * Meta Title field in *Training Module*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: training_module.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Training Module*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: training_module.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Training Module*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: training_module.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * Training Module document from Prismic
 *
 * - **API ID**: `training_module`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type TrainingModuleDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<TrainingModuleDocumentData>,
    'training_module',
    Lang
  >;

export type AllDocumentTypes =
  | AboutUsDocument
  | ContractorModuleDocument
  | FormsModuleDocument
  | HazardModuleDocument
  | HomeDocument
  | InspectionModuleDocument
  | PageDocument
  | PoliciesModuleDocument
  | TrainingModuleDocument;

/**
 * Primary content in *AboutJohn → Default → Primary*
 */
export interface AboutJohnSliceDefaultPrimary {
  /**
   * Eyebrow Text field in *AboutJohn → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: about_john.default.primary.eyebrow_text
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  eyebrow_text: prismic.KeyTextField;

  /**
   * Section Title field in *AboutJohn → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: about_john.default.primary.section_title
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  section_title: prismic.KeyTextField;

  /**
   * Section Subtitle field in *AboutJohn → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: about_john.default.primary.section_subtitle
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  section_subtitle: prismic.RichTextField;

  /**
   * Section Description field in *AboutJohn → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: about_john.default.primary.section_description
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  section_description: prismic.RichTextField;

  /**
   * John Image field in *AboutJohn → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: about_john.default.primary.john_image
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  john_image: prismic.ImageField<never>;
}

/**
 * Default variation for AboutJohn Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type AboutJohnSliceDefault = prismic.SharedSliceVariation<
  'default',
  Simplify<AboutJohnSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *AboutJohn*
 */
type AboutJohnSliceVariation = AboutJohnSliceDefault;

/**
 * AboutJohn Shared Slice
 *
 * - **API ID**: `about_john`
 * - **Description**: AboutJohn
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type AboutJohnSlice = prismic.SharedSlice<
  'about_john',
  AboutJohnSliceVariation
>;

/**
 * Item in *CheckList → Default → Primary → Check List*
 */
export interface BulletListSliceDefaultPrimaryCheckListItem {
  /**
   * Item Title field in *CheckList → Default → Primary → Check List*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: bullet_list.default.primary.check_list[].item_title
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  item_title: prismic.KeyTextField;

  /**
   * Item Description field in *CheckList → Default → Primary → Check List*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: bullet_list.default.primary.check_list[].item_description
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  item_description: prismic.RichTextField;
}

/**
 * Primary content in *CheckList → Default → Primary*
 */
export interface BulletListSliceDefaultPrimary {
  /**
   * Section Title field in *CheckList → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: bullet_list.default.primary.section_title
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  section_title: prismic.KeyTextField;

  /**
   * Section Subtitle field in *CheckList → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: bullet_list.default.primary.section_subtitle
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  section_subtitle: prismic.RichTextField;

  /**
   * Section Image field in *CheckList → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: bullet_list.default.primary.section_image
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  section_image: prismic.ImageField<never>;

  /**
   * Check List field in *CheckList → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: bullet_list.default.primary.check_list[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  check_list: prismic.GroupField<
    Simplify<BulletListSliceDefaultPrimaryCheckListItem>
  >;

  /**
   * Section Image Placeholder field in *CheckList → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: bullet_list.default.primary.section_image_placeholder
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  section_image_placeholder: prismic.RichTextField;
}

/**
 * Default variation for CheckList Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type BulletListSliceDefault = prismic.SharedSliceVariation<
  'default',
  Simplify<BulletListSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *CheckList*
 */
type BulletListSliceVariation = BulletListSliceDefault;

/**
 * CheckList Shared Slice
 *
 * - **API ID**: `bullet_list`
 * - **Description**: BulletList
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type BulletListSlice = prismic.SharedSlice<
  'bullet_list',
  BulletListSliceVariation
>;

/**
 * Item in *CallToAction → Default → Primary → Stats*
 */
export interface CallToActionSliceDefaultPrimaryStatsItem {
  /**
   * Number field in *CallToAction → Default → Primary → Stats*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: call_to_action.default.primary.stats[].number
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  number: prismic.KeyTextField;

  /**
   * Description field in *CallToAction → Default → Primary → Stats*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: call_to_action.default.primary.stats[].description
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  description: prismic.KeyTextField;
}

/**
 * Primary content in *CallToAction → Default → Primary*
 */
export interface CallToActionSliceDefaultPrimary {
  /**
   * Section Title field in *CallToAction → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: call_to_action.default.primary.section_title
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  section_title: prismic.KeyTextField;

  /**
   * Section Subtitle field in *CallToAction → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: call_to_action.default.primary.section_subtitle
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  section_subtitle: prismic.KeyTextField;

  /**
   * Stats field in *CallToAction → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: call_to_action.default.primary.stats[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  stats: prismic.GroupField<Simplify<CallToActionSliceDefaultPrimaryStatsItem>>;
}

/**
 * Default variation for CallToAction Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type CallToActionSliceDefault = prismic.SharedSliceVariation<
  'default',
  Simplify<CallToActionSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *CallToAction*
 */
type CallToActionSliceVariation = CallToActionSliceDefault;

/**
 * CallToAction Shared Slice
 *
 * - **API ID**: `call_to_action`
 * - **Description**: CallToAction
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type CallToActionSlice = prismic.SharedSlice<
  'call_to_action',
  CallToActionSliceVariation
>;

/**
 * Item in *Companies → Default → Primary → Companies*
 */
export interface CompaniesSliceDefaultPrimaryCompaniesItem {
  /**
   * Company Logo field in *Companies → Default → Primary → Companies*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: companies.default.primary.companies[].company_logo
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  company_logo: prismic.ImageField<never>;
}

/**
 * Primary content in *Companies → Default → Primary*
 */
export interface CompaniesSliceDefaultPrimary {
  /**
   * Companies field in *Companies → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: companies.default.primary.companies[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  companies: prismic.GroupField<
    Simplify<CompaniesSliceDefaultPrimaryCompaniesItem>
  >;
}

/**
 * Default variation for Companies Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type CompaniesSliceDefault = prismic.SharedSliceVariation<
  'default',
  Simplify<CompaniesSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Companies*
 */
type CompaniesSliceVariation = CompaniesSliceDefault;

/**
 * Companies Shared Slice
 *
 * - **API ID**: `companies`
 * - **Description**: Companies
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type CompaniesSlice = prismic.SharedSlice<
  'companies',
  CompaniesSliceVariation
>;

/**
 * Item in *ComplianceAudit → Default → Primary → Questions*
 */
export interface ComplianceAuditSliceDefaultPrimaryQuestionsItem {
  /**
   * Question Item field in *ComplianceAudit → Default → Primary → Questions*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: compliance_audit.default.primary.questions[].question_item
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  question_item: prismic.RichTextField;
}

/**
 * Item in *ComplianceAudit → Default → Primary → Answers Tips*
 */
export interface ComplianceAuditSliceDefaultPrimaryAnswersTipsItem {
  /**
   * Tip Title field in *ComplianceAudit → Default → Primary → Answers Tips*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: compliance_audit.default.primary.answers_tips[].tip_title
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  tip_title: prismic.KeyTextField;

  /**
   * Tip Description field in *ComplianceAudit → Default → Primary → Answers Tips*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: compliance_audit.default.primary.answers_tips[].tip_description
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  tip_description: prismic.RichTextField;

  /**
   * Level field in *ComplianceAudit → Default → Primary → Answers Tips*
   *
   * - **Field Type**: Number
   * - **Placeholder**: *None*
   * - **API ID Path**: compliance_audit.default.primary.answers_tips[].level
   * - **Documentation**: https://prismic.io/docs/fields/number
   */
  level: prismic.NumberField;
}

/**
 * Primary content in *ComplianceAudit → Default → Primary*
 */
export interface ComplianceAuditSliceDefaultPrimary {
  /**
   * Eyebrow Text field in *ComplianceAudit → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: compliance_audit.default.primary.eyebrow_text
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  eyebrow_text: prismic.KeyTextField;

  /**
   * Section Title field in *ComplianceAudit → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: compliance_audit.default.primary.section_title
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  section_title: prismic.KeyTextField;

  /**
   * Section Subtitle field in *ComplianceAudit → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: compliance_audit.default.primary.section_subtitle
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  section_subtitle: prismic.RichTextField;

  /**
   * Questions field in *ComplianceAudit → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: compliance_audit.default.primary.questions[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  questions: prismic.GroupField<
    Simplify<ComplianceAuditSliceDefaultPrimaryQuestionsItem>
  >;

  /**
   * Answers Tips field in *ComplianceAudit → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: compliance_audit.default.primary.answers_tips[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  answers_tips: prismic.GroupField<
    Simplify<ComplianceAuditSliceDefaultPrimaryAnswersTipsItem>
  >;
}

/**
 * Default variation for ComplianceAudit Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type ComplianceAuditSliceDefault = prismic.SharedSliceVariation<
  'default',
  Simplify<ComplianceAuditSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *ComplianceAudit*
 */
type ComplianceAuditSliceVariation = ComplianceAuditSliceDefault;

/**
 * ComplianceAudit Shared Slice
 *
 * - **API ID**: `compliance_audit`
 * - **Description**: ComplianceAudit
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type ComplianceAuditSlice = prismic.SharedSlice<
  'compliance_audit',
  ComplianceAuditSliceVariation
>;

/**
 * Primary content in *ContactUs → Default → Primary*
 */
export interface ContactUsSliceDefaultPrimary {
  /**
   * Section Title field in *ContactUs → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: contact_us.default.primary.section_title
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  section_title: prismic.KeyTextField;

  /**
   * Section Description field in *ContactUs → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: contact_us.default.primary.section_description
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  section_description: prismic.RichTextField;

  /**
   * Contact Number field in *ContactUs → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: contact_us.default.primary.contact_number
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  contact_number: prismic.KeyTextField;

  /**
   * Contact Email field in *ContactUs → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: contact_us.default.primary.contact_email
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  contact_email: prismic.KeyTextField;

  /**
   * Form Title field in *ContactUs → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Send us a message
   * - **API ID Path**: contact_us.default.primary.form_title
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  form_title: prismic.KeyTextField;
}

/**
 * Default variation for ContactUs Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type ContactUsSliceDefault = prismic.SharedSliceVariation<
  'default',
  Simplify<ContactUsSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *ContactUs*
 */
type ContactUsSliceVariation = ContactUsSliceDefault;

/**
 * ContactUs Shared Slice
 *
 * - **API ID**: `contact_us`
 * - **Description**: ContactUs
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type ContactUsSlice = prismic.SharedSlice<
  'contact_us',
  ContactUsSliceVariation
>;

/**
 * Item in *Faq → Default → Primary → FAQs*
 */
export interface FaqSliceDefaultPrimaryFaqsItem {
  /**
   * Question Item field in *Faq → Default → Primary → FAQs*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: faq.default.primary.faqs[].question_item
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  question_item: prismic.RichTextField;

  /**
   * Answer Item field in *Faq → Default → Primary → FAQs*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: faq.default.primary.faqs[].answer_item
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  answer_item: prismic.RichTextField;
}

/**
 * Primary content in *Faq → Default → Primary*
 */
export interface FaqSliceDefaultPrimary {
  /**
   * Section Title field in *Faq → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: faq.default.primary.section_title
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  section_title: prismic.KeyTextField;

  /**
   * Section Subtitle field in *Faq → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: faq.default.primary.section_subtitle
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  section_subtitle: prismic.RichTextField;

  /**
   * FAQs field in *Faq → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: faq.default.primary.faqs[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  faqs: prismic.GroupField<Simplify<FaqSliceDefaultPrimaryFaqsItem>>;
}

/**
 * Default variation for Faq Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type FaqSliceDefault = prismic.SharedSliceVariation<
  'default',
  Simplify<FaqSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Faq*
 */
type FaqSliceVariation = FaqSliceDefault;

/**
 * Faq Shared Slice
 *
 * - **API ID**: `faq`
 * - **Description**: Faq
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type FaqSlice = prismic.SharedSlice<'faq', FaqSliceVariation>;

/**
 * Item in *FinancialRelief → Default → Primary → Cards*
 */
export interface FinancialReliefSliceDefaultPrimaryCardsItem {
  /**
   * Card Icon field in *FinancialRelief → Default → Primary → Cards*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: financial_relief.default.primary.cards[].card_icon
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  card_icon: prismic.ImageField<never>;

  /**
   * Card Title field in *FinancialRelief → Default → Primary → Cards*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: financial_relief.default.primary.cards[].card_title
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  card_title: prismic.KeyTextField;

  /**
   * Card Subtitle field in *FinancialRelief → Default → Primary → Cards*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: financial_relief.default.primary.cards[].card_subtitle
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  card_subtitle: prismic.KeyTextField;

  /**
   * Card Text field in *FinancialRelief → Default → Primary → Cards*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: financial_relief.default.primary.cards[].card_text
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  card_text: prismic.KeyTextField;
}

/**
 * Item in *FinancialRelief → Default → Primary → Financial Table*
 */
export interface FinancialReliefSliceDefaultPrimaryFinancialTableItem {
  /**
   * Category of Loss field in *FinancialRelief → Default → Primary → Financial Table*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: financial_relief.default.primary.financial_table[].category_of_loss
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  category_of_loss: prismic.KeyTextField;

  /**
   * The Paper Way Costs field in *FinancialRelief → Default → Primary → Financial Table*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: financial_relief.default.primary.financial_table[].the_paper_way_costs
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  the_paper_way_costs: prismic.KeyTextField;

  /**
   * Your Safety Portal Result field in *FinancialRelief → Default → Primary → Financial Table*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: financial_relief.default.primary.financial_table[].your_safety_portal_result
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  your_safety_portal_result: prismic.KeyTextField;
}

/**
 * Item in *FinancialRelief → Default → Primary → Zero Claim Item*
 */
export interface FinancialReliefSliceDefaultPrimaryZeroClaimItemTitleItem {
  /**
   * Zero Claim Item Title field in *FinancialRelief → Default → Primary → Zero Claim Item*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: financial_relief.default.primary.zero_claim_item_title[].zero_claim_item_title
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  zero_claim_item_title: prismic.KeyTextField;

  /**
   * Zero Claim Item Description field in *FinancialRelief → Default → Primary → Zero Claim Item*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: financial_relief.default.primary.zero_claim_item_title[].zero_claim_item_description
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  zero_claim_item_description: prismic.KeyTextField;
}

/**
 * Primary content in *FinancialRelief → Default → Primary*
 */
export interface FinancialReliefSliceDefaultPrimary {
  /**
   * Section Title field in *FinancialRelief → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: financial_relief.default.primary.section_title
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  section_title: prismic.KeyTextField;

  /**
   * Section Subtitle field in *FinancialRelief → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: financial_relief.default.primary.section_subtitle
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  section_subtitle: prismic.RichTextField;

  /**
   * Cards field in *FinancialRelief → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: financial_relief.default.primary.cards[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  cards: prismic.GroupField<
    Simplify<FinancialReliefSliceDefaultPrimaryCardsItem>
  >;

  /**
   * Section Title 2 field in *FinancialRelief → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: financial_relief.default.primary.section_title_2
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  section_title_2: prismic.KeyTextField;

  /**
   * Section Subtitle 2 field in *FinancialRelief → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: financial_relief.default.primary.section_subtitle_2
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  section_subtitle_2: prismic.KeyTextField;

  /**
   * Financial Table field in *FinancialRelief → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: financial_relief.default.primary.financial_table[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  financial_table: prismic.GroupField<
    Simplify<FinancialReliefSliceDefaultPrimaryFinancialTableItem>
  >;

  /**
   * Zero Claim Card Title field in *FinancialRelief → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: financial_relief.default.primary.zero_claim_title
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  zero_claim_title: prismic.KeyTextField;

  /**
   * Zero Claim Item field in *FinancialRelief → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: financial_relief.default.primary.zero_claim_item_title[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  zero_claim_item_title: prismic.GroupField<
    Simplify<FinancialReliefSliceDefaultPrimaryZeroClaimItemTitleItem>
  >;
}

/**
 * Default variation for FinancialRelief Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type FinancialReliefSliceDefault = prismic.SharedSliceVariation<
  'default',
  Simplify<FinancialReliefSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *FinancialRelief*
 */
type FinancialReliefSliceVariation = FinancialReliefSliceDefault;

/**
 * FinancialRelief Shared Slice
 *
 * - **API ID**: `financial_relief`
 * - **Description**: FinancialRelief
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type FinancialReliefSlice = prismic.SharedSlice<
  'financial_relief',
  FinancialReliefSliceVariation
>;

/**
 * Item in *HeroSection → Default → Primary → Stats*
 */
export interface HeroSectionSliceDefaultPrimaryStatsItem {
  /**
   * Number field in *HeroSection → Default → Primary → Stats*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_section.default.primary.stats[].number
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  number: prismic.KeyTextField;

  /**
   * Description field in *HeroSection → Default → Primary → Stats*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_section.default.primary.stats[].description
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  description: prismic.KeyTextField;
}

/**
 * Primary content in *HeroSection → Default → Primary*
 */
export interface HeroSectionSliceDefaultPrimary {
  /**
   * Subtitle field in *HeroSection → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_section.default.primary.subtitle
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  subtitle: prismic.KeyTextField;

  /**
   * Hero Title field in *HeroSection → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_section.default.primary.hero_title
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  hero_title: prismic.KeyTextField;

  /**
   * Hero Description field in *HeroSection → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_section.default.primary.hero_description
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  hero_description: prismic.KeyTextField;

  /**
   * Hero Image field in *HeroSection → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_section.default.primary.hero_image
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  hero_image: prismic.ImageField<never>;

  /**
   * Stats field in *HeroSection → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_section.default.primary.stats[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  stats: prismic.GroupField<Simplify<HeroSectionSliceDefaultPrimaryStatsItem>>;
}

/**
 * Default variation for HeroSection Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type HeroSectionSliceDefault = prismic.SharedSliceVariation<
  'default',
  Simplify<HeroSectionSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *HeroSection*
 */
type HeroSectionSliceVariation = HeroSectionSliceDefault;

/**
 * HeroSection Shared Slice
 *
 * - **API ID**: `hero_section`
 * - **Description**: HeroSection
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type HeroSectionSlice = prismic.SharedSlice<
  'hero_section',
  HeroSectionSliceVariation
>;

/**
 * Item in *Industries → Default → Primary → Industries*
 */
export interface HowWeCanWelpSliceDefaultPrimaryIndustriesItem {
  /**
   * Industry Icon field in *Industries → Default → Primary → Industries*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: how_we_can_welp.default.primary.industries[].industry_icon
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  industry_icon: prismic.ImageField<never>;

  /**
   * Industry Item field in *Industries → Default → Primary → Industries*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: how_we_can_welp.default.primary.industries[].industry_item
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  industry_item: prismic.KeyTextField;

  /**
   * Description field in *Industries → Default → Primary → Industries*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: how_we_can_welp.default.primary.industries[].description
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  description: prismic.RichTextField;
}

/**
 * Primary content in *Industries → Default → Primary*
 */
export interface HowWeCanWelpSliceDefaultPrimary {
  /**
   * Section Title field in *Industries → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: how_we_can_welp.default.primary.section_title
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  section_title: prismic.KeyTextField;

  /**
   * Section Description field in *Industries → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: how_we_can_welp.default.primary.section_description
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  section_description: prismic.RichTextField;

  /**
   * Industries field in *Industries → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: how_we_can_welp.default.primary.industries[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  industries: prismic.GroupField<
    Simplify<HowWeCanWelpSliceDefaultPrimaryIndustriesItem>
  >;
}

/**
 * Default variation for Industries Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type HowWeCanWelpSliceDefault = prismic.SharedSliceVariation<
  'default',
  Simplify<HowWeCanWelpSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Industries*
 */
type HowWeCanWelpSliceVariation = HowWeCanWelpSliceDefault;

/**
 * Industries Shared Slice
 *
 * - **API ID**: `how_we_can_welp`
 * - **Description**: Industries
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type HowWeCanWelpSlice = prismic.SharedSlice<
  'how_we_can_welp',
  HowWeCanWelpSliceVariation
>;

/**
 * Primary content in *Legislative → Default → Primary*
 */
export interface LegislativeSliceDefaultPrimary {
  /**
   * Section Title field in *Legislative → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: legislative.default.primary.section_title
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  section_title: prismic.KeyTextField;

  /**
   * Section Subtitle field in *Legislative → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: legislative.default.primary.section_subtitle
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  section_subtitle: prismic.RichTextField;

  /**
   * WHS Image field in *Legislative → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: legislative.default.primary.whs_image
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  whs_image: prismic.ImageField<never>;
}

/**
 * Default variation for Legislative Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type LegislativeSliceDefault = prismic.SharedSliceVariation<
  'default',
  Simplify<LegislativeSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Legislative*
 */
type LegislativeSliceVariation = LegislativeSliceDefault;

/**
 * Legislative Shared Slice
 *
 * - **API ID**: `legislative`
 * - **Description**: Legislative
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type LegislativeSlice = prismic.SharedSlice<
  'legislative',
  LegislativeSliceVariation
>;

/**
 * Item in *OurMissionVision → Default → Primary → Cards*
 */
export interface OurMissionSliceDefaultPrimaryCardItem {
  /**
   * Card Eyebrow Text field in *OurMissionVision → Default → Primary → Cards*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: our_mission.default.primary.card[].card_eyebrow_text
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  card_eyebrow_text: prismic.KeyTextField;

  /**
   * Card Title field in *OurMissionVision → Default → Primary → Cards*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: our_mission.default.primary.card[].card_title
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  card_title: prismic.KeyTextField;

  /**
   * Card Subtitle field in *OurMissionVision → Default → Primary → Cards*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: our_mission.default.primary.card[].card_subtitle
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  card_subtitle: prismic.RichTextField;

  /**
   * Card Description field in *OurMissionVision → Default → Primary → Cards*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: our_mission.default.primary.card[].card_description
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  card_description: prismic.RichTextField;
}

/**
 * Primary content in *OurMissionVision → Default → Primary*
 */
export interface OurMissionSliceDefaultPrimary {
  /**
   * Cards field in *OurMissionVision → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: our_mission.default.primary.card[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  card: prismic.GroupField<Simplify<OurMissionSliceDefaultPrimaryCardItem>>;
}

/**
 * Default variation for OurMissionVision Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type OurMissionSliceDefault = prismic.SharedSliceVariation<
  'default',
  Simplify<OurMissionSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *OurMissionVision*
 */
type OurMissionSliceVariation = OurMissionSliceDefault;

/**
 * OurMissionVision Shared Slice
 *
 * - **API ID**: `our_mission`
 * - **Description**: OurMission
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type OurMissionSlice = prismic.SharedSlice<
  'our_mission',
  OurMissionSliceVariation
>;

/**
 * Item in *Modules → Default → Primary → Modules*
 */
export interface PlatformAppsSliceDefaultPrimaryModulesItem {
  /**
   * Module Logo field in *Modules → Default → Primary → Modules*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: platform_apps.default.primary.modules[].module_logo
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  module_logo: prismic.ImageField<never>;

  /**
   * Module Name field in *Modules → Default → Primary → Modules*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: platform_apps.default.primary.modules[].module_name
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  module_name: prismic.KeyTextField;

  /**
   * Module Description field in *Modules → Default → Primary → Modules*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: platform_apps.default.primary.modules[].module_description
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  module_description: prismic.RichTextField;
}

/**
 * Primary content in *Modules → Default → Primary*
 */
export interface PlatformAppsSliceDefaultPrimary {
  /**
   * Section Title field in *Modules → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: platform_apps.default.primary.section_title
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  section_title: prismic.KeyTextField;

  /**
   * Section Subtitle field in *Modules → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: platform_apps.default.primary.section_subtitle
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  section_subtitle: prismic.RichTextField;

  /**
   * Modules field in *Modules → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: platform_apps.default.primary.modules[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  modules: prismic.GroupField<
    Simplify<PlatformAppsSliceDefaultPrimaryModulesItem>
  >;
}

/**
 * Default variation for Modules Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type PlatformAppsSliceDefault = prismic.SharedSliceVariation<
  'default',
  Simplify<PlatformAppsSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Modules*
 */
type PlatformAppsSliceVariation = PlatformAppsSliceDefault;

/**
 * Modules Shared Slice
 *
 * - **API ID**: `platform_apps`
 * - **Description**: PlatformApps
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type PlatformAppsSlice = prismic.SharedSlice<
  'platform_apps',
  PlatformAppsSliceVariation
>;

/**
 * Primary content in *SubpageHeroSection → Default → Primary*
 */
export interface SubpageHeroSectionSliceDefaultPrimary {
  /**
   * Eyebrow Text field in *SubpageHeroSection → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: subpage_hero_section.default.primary.eyebrow_text
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  eyebrow_text: prismic.KeyTextField;

  /**
   * Hero Title field in *SubpageHeroSection → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: subpage_hero_section.default.primary.hero_title
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  hero_title: prismic.KeyTextField;

  /**
   * Hero Description field in *SubpageHeroSection → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: subpage_hero_section.default.primary.hero_description
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  hero_description: prismic.RichTextField;

  /**
   * Hero Image field in *SubpageHeroSection → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: subpage_hero_section.default.primary.hero_image
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  hero_image: prismic.ImageField<never>;

  /**
   * Primary CTA field in *SubpageHeroSection → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: subpage_hero_section.default.primary.primary_cta
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  primary_cta: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;

  /**
   * Secondary CTA field in *SubpageHeroSection → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: subpage_hero_section.default.primary.secondary_cta
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  secondary_cta: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;

  /**
   * Hero Image Placeholder field in *SubpageHeroSection → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: subpage_hero_section.default.primary.hero_image_placeholder
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  hero_image_placeholder: prismic.RichTextField;
}

/**
 * Default variation for SubpageHeroSection Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type SubpageHeroSectionSliceDefault = prismic.SharedSliceVariation<
  'default',
  Simplify<SubpageHeroSectionSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *SubpageHeroSection*
 */
type SubpageHeroSectionSliceVariation = SubpageHeroSectionSliceDefault;

/**
 * SubpageHeroSection Shared Slice
 *
 * - **API ID**: `subpage_hero_section`
 * - **Description**: SubpageHeroSection
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type SubpageHeroSectionSlice = prismic.SharedSlice<
  'subpage_hero_section',
  SubpageHeroSectionSliceVariation
>;

/**
 * Item in *Testimonial → Default → Primary → Items*
 */
export interface TestimonialSliceDefaultPrimaryItemsItem {
  /**
   * Stars field in *Testimonial → Default → Primary → Items*
   *
   * - **Field Type**: Number
   * - **Placeholder**: *None*
   * - **API ID Path**: testimonial.default.primary.items[].stars
   * - **Documentation**: https://prismic.io/docs/fields/number
   */
  stars: prismic.NumberField;

  /**
   * Quote field in *Testimonial → Default → Primary → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: testimonial.default.primary.items[].quote
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  quote: prismic.RichTextField;

  /**
   * Author field in *Testimonial → Default → Primary → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: testimonial.default.primary.items[].author
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  author: prismic.RichTextField;

  /**
   * Role field in *Testimonial → Default → Primary → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: testimonial.default.primary.items[].role
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  role: prismic.RichTextField;

  /**
   * Company field in *Testimonial → Default → Primary → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: testimonial.default.primary.items[].company
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  company: prismic.KeyTextField;
}

/**
 * Primary content in *Testimonial → Default → Primary*
 */
export interface TestimonialSliceDefaultPrimary {
  /**
   * Section Title field in *Testimonial → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: testimonial.default.primary.section_title
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  section_title: prismic.RichTextField;

  /**
   * Section Subtitle field in *Testimonial → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: testimonial.default.primary.section_subtitle
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  section_subtitle: prismic.RichTextField;

  /**
   * Items field in *Testimonial → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: testimonial.default.primary.items[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  items: prismic.GroupField<Simplify<TestimonialSliceDefaultPrimaryItemsItem>>;
}

/**
 * Default variation for Testimonial Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type TestimonialSliceDefault = prismic.SharedSliceVariation<
  'default',
  Simplify<TestimonialSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Testimonial*
 */
type TestimonialSliceVariation = TestimonialSliceDefault;

/**
 * Testimonial Shared Slice
 *
 * - **API ID**: `testimonial`
 * - **Description**: Testimonial
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type TestimonialSlice = prismic.SharedSlice<
  'testimonial',
  TestimonialSliceVariation
>;

/**
 * Item in *Timeline → Default → Primary → Timeline*
 */
export interface TimelineSectionSliceDefaultPrimaryTimelineItem {
  /**
   * Year field in *Timeline → Default → Primary → Timeline*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: timeline_section.default.primary.timeline[].year
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  year: prismic.KeyTextField;

  /**
   * Title field in *Timeline → Default → Primary → Timeline*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: timeline_section.default.primary.timeline[].title
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  title: prismic.RichTextField;

  /**
   * Description field in *Timeline → Default → Primary → Timeline*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: timeline_section.default.primary.timeline[].description
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  description: prismic.RichTextField;
}

/**
 * Primary content in *Timeline → Default → Primary*
 */
export interface TimelineSectionSliceDefaultPrimary {
  /**
   * Section Title field in *Timeline → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: timeline_section.default.primary.section_title
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  section_title: prismic.KeyTextField;

  /**
   * Section Subtitle field in *Timeline → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: timeline_section.default.primary.section_subtitle
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  section_subtitle: prismic.RichTextField;

  /**
   * Timeline field in *Timeline → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: timeline_section.default.primary.timeline[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  timeline: prismic.GroupField<
    Simplify<TimelineSectionSliceDefaultPrimaryTimelineItem>
  >;
}

/**
 * Default variation for Timeline Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type TimelineSectionSliceDefault = prismic.SharedSliceVariation<
  'default',
  Simplify<TimelineSectionSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Timeline*
 */
type TimelineSectionSliceVariation = TimelineSectionSliceDefault;

/**
 * Timeline Shared Slice
 *
 * - **API ID**: `timeline_section`
 * - **Description**: TimelineSection
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type TimelineSectionSlice = prismic.SharedSlice<
  'timeline_section',
  TimelineSectionSliceVariation
>;

/**
 * Item in *WhatWeDo → Default → Primary → Bento Box Cards*
 */
export interface WhatWeDoSliceDefaultPrimaryBentoBoxCardsItem {
  /**
   * Card Title field in *WhatWeDo → Default → Primary → Bento Box Cards*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: what_we_do.default.primary.bento_box_cards[].card_title
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  card_title: prismic.KeyTextField;

  /**
   * Card Description field in *WhatWeDo → Default → Primary → Bento Box Cards*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: what_we_do.default.primary.bento_box_cards[].card_description
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  card_description: prismic.RichTextField;

  /**
   * Card Icon field in *WhatWeDo → Default → Primary → Bento Box Cards*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: what_we_do.default.primary.bento_box_cards[].card_icon
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  card_icon: prismic.ImageField<never>;
}

/**
 * Primary content in *WhatWeDo → Default → Primary*
 */
export interface WhatWeDoSliceDefaultPrimary {
  /**
   * Section Title field in *WhatWeDo → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: what_we_do.default.primary.section_title
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  section_title: prismic.KeyTextField;

  /**
   * Section Subtitle field in *WhatWeDo → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: what_we_do.default.primary.section_subtitle
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  section_subtitle: prismic.RichTextField;

  /**
   * Bento Box Cards field in *WhatWeDo → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: what_we_do.default.primary.bento_box_cards[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  bento_box_cards: prismic.GroupField<
    Simplify<WhatWeDoSliceDefaultPrimaryBentoBoxCardsItem>
  >;
}

/**
 * Default variation for WhatWeDo Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type WhatWeDoSliceDefault = prismic.SharedSliceVariation<
  'default',
  Simplify<WhatWeDoSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *WhatWeDo*
 */
type WhatWeDoSliceVariation = WhatWeDoSliceDefault;

/**
 * WhatWeDo Shared Slice
 *
 * - **API ID**: `what_we_do`
 * - **Description**: WhatWeDo
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type WhatWeDoSlice = prismic.SharedSlice<
  'what_we_do',
  WhatWeDoSliceVariation
>;

/**
 * Item in *WhoIsItFor → Default → Primary → Who is it for items*
 */
export interface WhyChooseUsSliceDefaultPrimaryWhoIsItForItemsItem {
  /**
   * Card Icon field in *WhoIsItFor → Default → Primary → Who is it for items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: why_choose_us.default.primary.who_is_it_for_items[].card_icon
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  card_icon: prismic.KeyTextField;

  /**
   * Position Title field in *WhoIsItFor → Default → Primary → Who is it for items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: why_choose_us.default.primary.who_is_it_for_items[].position_title
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  position_title: prismic.KeyTextField;

  /**
   * Description field in *WhoIsItFor → Default → Primary → Who is it for items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: why_choose_us.default.primary.who_is_it_for_items[].description
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  description: prismic.RichTextField;
}

/**
 * Primary content in *WhoIsItFor → Default → Primary*
 */
export interface WhyChooseUsSliceDefaultPrimary {
  /**
   * Section Title field in *WhoIsItFor → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: why_choose_us.default.primary.section_title
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  section_title: prismic.KeyTextField;

  /**
   * Section Subtitle field in *WhoIsItFor → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: why_choose_us.default.primary.section_subtitle
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  section_subtitle: prismic.RichTextField;

  /**
   * Who is it for items field in *WhoIsItFor → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: why_choose_us.default.primary.who_is_it_for_items[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  who_is_it_for_items: prismic.GroupField<
    Simplify<WhyChooseUsSliceDefaultPrimaryWhoIsItForItemsItem>
  >;
}

/**
 * Default variation for WhoIsItFor Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type WhyChooseUsSliceDefault = prismic.SharedSliceVariation<
  'default',
  Simplify<WhyChooseUsSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *WhoIsItFor*
 */
type WhyChooseUsSliceVariation = WhyChooseUsSliceDefault;

/**
 * WhoIsItFor Shared Slice
 *
 * - **API ID**: `why_choose_us`
 * - **Description**: WhyChooseUs
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type WhyChooseUsSlice = prismic.SharedSlice<
  'why_choose_us',
  WhyChooseUsSliceVariation
>;

declare module '@prismicio/client' {
  interface CreateClient {
    (
      repositoryNameOrEndpoint: string,
      options?: prismic.ClientConfig
    ): prismic.Client<AllDocumentTypes>;
  }

  interface CreateWriteClient {
    (
      repositoryNameOrEndpoint: string,
      options: prismic.WriteClientConfig
    ): prismic.WriteClient<AllDocumentTypes>;
  }

  interface CreateMigration {
    (): prismic.Migration<AllDocumentTypes>;
  }

  namespace Content {
    export type {
      AboutUsDocument,
      AboutUsDocumentData,
      AboutUsDocumentDataSlicesSlice,
      ContractorModuleDocument,
      ContractorModuleDocumentData,
      ContractorModuleDocumentDataSlicesSlice,
      FormsModuleDocument,
      FormsModuleDocumentData,
      FormsModuleDocumentDataSlicesSlice,
      HazardModuleDocument,
      HazardModuleDocumentData,
      HazardModuleDocumentDataSlicesSlice,
      HomeDocument,
      HomeDocumentData,
      HomeDocumentDataSlicesSlice,
      InspectionModuleDocument,
      InspectionModuleDocumentData,
      InspectionModuleDocumentDataSlicesSlice,
      PageDocument,
      PageDocumentData,
      PageDocumentDataSlicesSlice,
      PoliciesModuleDocument,
      PoliciesModuleDocumentData,
      PoliciesModuleDocumentDataSlicesSlice,
      TrainingModuleDocument,
      TrainingModuleDocumentData,
      TrainingModuleDocumentDataSlicesSlice,
      AllDocumentTypes,
      AboutJohnSlice,
      AboutJohnSliceDefaultPrimary,
      AboutJohnSliceVariation,
      AboutJohnSliceDefault,
      BulletListSlice,
      BulletListSliceDefaultPrimaryCheckListItem,
      BulletListSliceDefaultPrimary,
      BulletListSliceVariation,
      BulletListSliceDefault,
      CallToActionSlice,
      CallToActionSliceDefaultPrimaryStatsItem,
      CallToActionSliceDefaultPrimary,
      CallToActionSliceVariation,
      CallToActionSliceDefault,
      CompaniesSlice,
      CompaniesSliceDefaultPrimaryCompaniesItem,
      CompaniesSliceDefaultPrimary,
      CompaniesSliceVariation,
      CompaniesSliceDefault,
      ComplianceAuditSlice,
      ComplianceAuditSliceDefaultPrimaryQuestionsItem,
      ComplianceAuditSliceDefaultPrimaryAnswersTipsItem,
      ComplianceAuditSliceDefaultPrimary,
      ComplianceAuditSliceVariation,
      ComplianceAuditSliceDefault,
      ContactUsSlice,
      ContactUsSliceDefaultPrimary,
      ContactUsSliceVariation,
      ContactUsSliceDefault,
      FaqSlice,
      FaqSliceDefaultPrimaryFaqsItem,
      FaqSliceDefaultPrimary,
      FaqSliceVariation,
      FaqSliceDefault,
      FinancialReliefSlice,
      FinancialReliefSliceDefaultPrimaryCardsItem,
      FinancialReliefSliceDefaultPrimaryFinancialTableItem,
      FinancialReliefSliceDefaultPrimaryZeroClaimItemTitleItem,
      FinancialReliefSliceDefaultPrimary,
      FinancialReliefSliceVariation,
      FinancialReliefSliceDefault,
      HeroSectionSlice,
      HeroSectionSliceDefaultPrimaryStatsItem,
      HeroSectionSliceDefaultPrimary,
      HeroSectionSliceVariation,
      HeroSectionSliceDefault,
      HowWeCanWelpSlice,
      HowWeCanWelpSliceDefaultPrimaryIndustriesItem,
      HowWeCanWelpSliceDefaultPrimary,
      HowWeCanWelpSliceVariation,
      HowWeCanWelpSliceDefault,
      LegislativeSlice,
      LegislativeSliceDefaultPrimary,
      LegislativeSliceVariation,
      LegislativeSliceDefault,
      OurMissionSlice,
      OurMissionSliceDefaultPrimaryCardItem,
      OurMissionSliceDefaultPrimary,
      OurMissionSliceVariation,
      OurMissionSliceDefault,
      PlatformAppsSlice,
      PlatformAppsSliceDefaultPrimaryModulesItem,
      PlatformAppsSliceDefaultPrimary,
      PlatformAppsSliceVariation,
      PlatformAppsSliceDefault,
      SubpageHeroSectionSlice,
      SubpageHeroSectionSliceDefaultPrimary,
      SubpageHeroSectionSliceVariation,
      SubpageHeroSectionSliceDefault,
      TestimonialSlice,
      TestimonialSliceDefaultPrimaryItemsItem,
      TestimonialSliceDefaultPrimary,
      TestimonialSliceVariation,
      TestimonialSliceDefault,
      TimelineSectionSlice,
      TimelineSectionSliceDefaultPrimaryTimelineItem,
      TimelineSectionSliceDefaultPrimary,
      TimelineSectionSliceVariation,
      TimelineSectionSliceDefault,
      WhatWeDoSlice,
      WhatWeDoSliceDefaultPrimaryBentoBoxCardsItem,
      WhatWeDoSliceDefaultPrimary,
      WhatWeDoSliceVariation,
      WhatWeDoSliceDefault,
      WhyChooseUsSlice,
      WhyChooseUsSliceDefaultPrimaryWhoIsItForItemsItem,
      WhyChooseUsSliceDefaultPrimary,
      WhyChooseUsSliceVariation,
      WhyChooseUsSliceDefault,
    };
  }
}
