// Code generated by Prismic. DO NOT EDIT.

import AboutJohn from "./AboutJohn";
import CheckList from "./CheckList";
import CallToAction from "./CallToAction";
import Companies from "./Companies";
import ComplianceAudit from "./ComplianceAudit";
import ContactUs from "./ContactUs";
import Faq from "./Faq";
import FinancialRelief from "./FinancialRelief";
import HeroSection from "./HeroSection";
import Industries from "./Industries";
import Legislative from "./Legislative";
import OurTeam from "./OurTeam";
import OurMissionVision from "./OurMissionVision";
import Modules from "./Modules";
import SubpageHeroSection from "./SubpageHeroSection";
import Testimonial from "./Testimonial";
import Timeline from "./Timeline";
import WhatWeDo from "./WhatWeDo";
import WhoIsItFor from "./WhoIsItFor";

export const components = {
<<<<<<< HEAD
  about_john: dynamic(() => import('./AboutJohn')),
  bullet_list: dynamic(() => import('./CheckList')),
  call_to_action: dynamic(() => import('./CallToAction')),
  companies: dynamic(() => import('./Companies')),
  compliance_audit: dynamic(() => import('./ComplianceAudit')),
  contact_us: dynamic(() => import('./ContactUs')),
  faq: dynamic(() => import('./Faq')),
  financial_relief: dynamic(() => import('./FinancialRelief')),
  hero_section: dynamic(() => import('./HeroSection')),
  how_we_can_welp: dynamic(() => import('./Industries')),
  legislative: dynamic(() => import('./Legislative')),
  meet_team: dynamic(() => import('./OurTeam')),
  our_mission: dynamic(() => import('./OurMissionVision')),
  platform_apps: dynamic(() => import('./Modules')),
  privacy_policy: dynamic(() => import('./PrivacyPolicy')),
  subpage_hero_section: dynamic(() => import('./SubpageHeroSection')),
  testimonial: dynamic(() => import('./Testimonial')),
  timeline_section: dynamic(() => import('./Timeline')),
  what_we_do: dynamic(() => import('./WhatWeDo')),
  why_choose_us: dynamic(() => import('./WhoIsItFor')),
};
=======
	about_john: AboutJohn,
	bullet_list: CheckList,
	call_to_action: CallToAction,
	companies: Companies,
	compliance_audit: ComplianceAudit,
	contact_us: ContactUs,
	faq: Faq,
	financial_relief: FinancialRelief,
	hero_section: HeroSection,
	how_we_can_welp: Industries,
	legislative: Legislative,
	meet_team: OurTeam,
	our_mission: OurMissionVision,
	platform_apps: Modules,
	subpage_hero_section: SubpageHeroSection,
	testimonial: Testimonial,
	timeline_section: Timeline,
	what_we_do: WhatWeDo,
	why_choose_us: WhoIsItFor
};
>>>>>>> 346d2b24a2aa69586c8aa76950183790e2f61a77
