// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from 'next/dynamic';

export const components = {
  bullet_list: dynamic(() => import('./CheckList')),
  call_to_action: dynamic(() => import('./CallToAction')),
  companies: dynamic(() => import('./Companies')),
  compliance_audit: dynamic(() => import('./ComplianceAudit')),
  contact_us: dynamic(() => import('./ContactUs')),
  faq: dynamic(() => import('./Faq')),
  financial_relief: dynamic(() => import('./FinancialRelief')),
  hero_section: dynamic(() => import('./HeroSection')),
  how_we_can_welp: dynamic(() => import('./Industries')),
  legislative: dynamic(() => import('./Legislative')),
  platform_apps: dynamic(() => import('./Modules')),
  subpage_hero_section: dynamic(() => import('./SubpageHeroSection')),
  testimonial: dynamic(() => import('./Testimonial')),
  why_choose_us: dynamic(() => import('./WhoIsItFor')),
};
