// lib/outrank.ts

/**
 * Outrank.so Programmatic SEO Data Integration
 * 
 * This utility handles fetching and formatting data generated by Outrank.
 * Currently, it uses mock data. When you are ready to connect Outrank:
 * 1. If using an API: Replace the mock arrays with a `fetch()` call to Outrank's endpoint.
 * 2. If using a JSON file: Import the JSON directly (e.g., `import data from '@/data/outrank.json'`).
 */

export type ProgrammaticSEOPage = {
  slug: string;
  title: string;
  metaDescription: string;
  h1: string;
  subtitle: string;
  contentBlocks: {
    heading: string;
    paragraph: string;
  }[];
  features: string[];
};

// Mock Data: Replace with real Outrank API/JSON data
const MOCK_INDUSTRY_DATA: ProgrammaticSEOPage[] = [
  {
    slug: 'construction',
    title: 'Safety Compliance Software for Construction | Your Safety Partners',
    metaDescription: 'Ensure OSHA compliance and streamline safety management on construction sites with our dedicated safety software.',
    h1: 'Construction Safety Compliance Software',
    subtitle: 'Built specifically for the unique hazards and fast-paced environment of construction sites.',
    contentBlocks: [
      { heading: 'Streamline Jobsite Inspections', paragraph: 'Conduct daily hazard assessments and tool-box talks directly from your mobile device.' },
      { heading: 'Manage Subcontractor Compliance', paragraph: 'Ensure every contractor on site has the proper certifications and training records before stepping foot on the job.' }
    ],
    features: ['Mobile Inspections', 'Contractor Portal', 'Offline Mode', 'Incident Reporting']
  },
  {
    slug: 'manufacturing',
    title: 'Manufacturing Safety & EHS Software | Your Safety Partners',
    metaDescription: 'Automate lock-out/tag-out procedures and manage factory floor safety with our manufacturing EHS software.',
    h1: 'Safety Management for Manufacturing',
    subtitle: 'Reduce downtime and protect your workers with streamlined EHS compliance for the factory floor.',
    contentBlocks: [
      { heading: 'Lockout/Tagout Automation', paragraph: 'Digitize your LOTO procedures to ensure absolute compliance and worker safety during machine maintenance.' },
      { heading: 'Real-time Hazard Tracking', paragraph: 'Empower floor workers to report near-misses and hazards instantly via QR codes.' }
    ],
    features: ['LOTO Management', 'QR Code Reporting', 'Training Matrix', 'Audit Trails']
  }
];

const MOCK_COMPARE_DATA: ProgrammaticSEOPage[] = [
  {
    slug: 'competitor-a',
    title: 'Your Safety Partners vs Competitor A | Best Alternative 2024',
    metaDescription: 'See why safety professionals are switching from Competitor A to Your Safety Partners for better compliance management.',
    h1: 'The Better Alternative to Competitor A',
    subtitle: 'Stop overpaying for clunky legacy software. See how we compare.',
    contentBlocks: [
      { heading: 'Modern, Intuitive Interface', paragraph: 'Unlike Competitor A\'s outdated 90s interface, our platform is built for the modern workforce, requiring zero training to use.' },
      { heading: 'Transparent Pricing', paragraph: 'We don\'t hide our pricing behind aggressive sales calls. Get all features without the enterprise bloat.' }
    ],
    features: ['No Implementation Fees', 'Free Support', 'Unlimited Users', 'Modern UI']
  }
];

/**
 * Fetch all industry pages (used for generating static params and index pages)
 */
export async function getIndustries(): Promise<ProgrammaticSEOPage[]> {
  // TODO: Replace with real data fetch
  return MOCK_INDUSTRY_DATA;
}

/**
 * Fetch a specific industry page by slug
 */
export async function getIndustryBySlug(slug: string): Promise<ProgrammaticSEOPage | null> {
  // TODO: Replace with real data fetch
  const page = MOCK_INDUSTRY_DATA.find(p => p.slug === slug);
  return page || null;
}

/**
 * Fetch all comparison pages (used for generating static params and index pages)
 */
export async function getComparisons(): Promise<ProgrammaticSEOPage[]> {
  // TODO: Replace with real data fetch
  return MOCK_COMPARE_DATA;
}

/**
 * Fetch a specific comparison page by slug
 */
export async function getComparisonBySlug(slug: string): Promise<ProgrammaticSEOPage | null> {
  // TODO: Replace with real data fetch
  const page = MOCK_COMPARE_DATA.find(p => p.slug === slug);
  return page || null;
}
